# Generated by Django 4.2 on 2023-05-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cronograma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=225)),
                ('conteudo', models.TextField()),
                ('cronograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cronograma.cronograma')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacao.publicacao')),
            ],
        ),
    ]
